database:
  connection_string: "postgresql://smart:smart1234@localhost:5432/strange?sslmode=disable"

server:
  port: 8090
  host: "0.0.0.0"

endpoints:
  - path: "/api/users"
    method: "GET"
    response:
      status: 200
      body: '{"users": [{"id": 1, "name": "John"}, {"id": 2, "name": "Jane"}]}'
      headers:
        Content-Type: "application/json"
  
  - path: "/api/users"
    method: "POST"
    response:
      status: 201
      body: '{"result": "success"}'
      headers:
        Content-Type: "application/json"
  
  - path: "/api/health"
    method: "GET"
    response:
      status: 200
      body: '{"status": "OK", "timestamp": "{{.timestamp}}"}'
      headers:
        Content-Type: "application/json"
  
  - path: "/api/products/{id}"
    method: "POST"
    response:
      status: 200
      body: '{"result": "success"}'
      headers:
        Content-Type: "application/json"

  - path: "/api/tempo"
    method: "POST"
    response:
      status: 201
      body: '{"result": "success"}'
      headers:
        Content-Type: "application/json"

  - path: "/hands/left"
    method: "POST"
    response:
      status: 201
      body: '{"result": "success"}'
      headers:
        Content-Type: "application/json"
